---
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Insert Index Page
  copy:
    src: index.html
    dest: "{{ nginx_site_directory }}"

- name: Insert ansible logo
  copy:
    src: ansible-logo.jpg
    dest: "{{ nginx_site_directory }}"

- name: Start NGiNX
  service:
    name: nginx
    state: started
